/* tslint:disable */
/* eslint-disable */
/**
 * Code Kanban - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<
            Responded,
            any,
            RequestConfig,
            Response,
            ResponseHeader,
            L1Cache,
            L2Cache,
            SE
          >,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default,
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>,
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface CreateNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 内容
   */
  content: string;
  /**
   * 标签页名称
   */
  name: string;
  /**
   * 项目ID（为空表示全局笔记）
   */
  projectId?: string;
}
export interface CreateProjectInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 项目描述
   */
  description: string;
  /**
   * 是否隐藏真实路径
   */
  hidePath?: boolean;
  /**
   * 项目名称
   */
  name: string;
  /**
   * 本地项目目录路径（可非 Git 仓库）
   */
  path: string;
  /**
   * Worktree 基础路径（可选，默认为项目目录下的 .worktrees 子目录）
   */
  worktreeBasePath?: string;
}
export interface DeveloperConfig {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  enableTerminalScrollback: boolean;
  enableTerminalStateSnapshot: boolean;
  webSessionCodexClientName: string;
  webSessionCodexClientTitle: string;
  webSessionCodexClientVersion: string;
  webSessionCodexDefaultModel: string;
  webSessionCodexDefaultPermissionLevel: string;
  webSessionCodexDefaultReasoningEffort: string;
  webSessionCodexDefaultSyncMode: string;
  webSessionAutoRetryDefaults: WebSessionAutoRetryDefaultsConfig;
  webSessionActiveCallTimeout: WebSessionActiveCallTimeoutConfig;
}
export interface WebSessionAutoRetryDefaultsConfig {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  dispatchPendingOnFailure: boolean;
  maxAttempts: number;
  preset: string;
  scope: string;
}
export interface WebSessionActiveCallTimeoutConfig {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  callKinds: WebSessionActiveCallTimeoutKindsConfig;
  customTimeoutSeconds: number;
  enabledMode: string;
  promptTemplate: string;
  timeoutMode: string;
}
export interface WebSessionActiveCallTimeoutKindsConfig {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  command: boolean;
  mcp: boolean;
  tool: boolean;
  useDefault: boolean;
}
export interface OpenEditorInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 自定义命令，使用 ${path} 作为路径占位符
   */
  customCommand?: string;
  /**
   * 目标编辑器(vscode/cursor/trae/zed/custom)
   */
  editor: string;
  /**
   * 目标路径
   */
  path: string;
}
export interface OpenPathInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 目标路径
   */
  path: string;
}
export interface UploadClipboardImageInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 图片数据（base64 编码）
   */
  data: string;
  /**
   * 文件名
   */
  fileName: string;
}
export interface MessageResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 提示信息
   */
  message: string;
}
export interface Project {
  createdAt: string;
  defaultBranch: string | null;
  deletedAt: string | null;
  description: string | null;
  hidePath: boolean;
  id: string;
  lastAccessedAt: string | null;
  lastSyncAt: string | null;
  name: string;
  path: string;
  priority: number | null;
  remoteUrl: string | null;
  updatedAt: string;
  worktreeBasePath: string | null;
}
export interface ItemsResponseProjectBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: Project[] | null;
}
export interface CheckUpdateResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 当前版本
   */
  currentVersion: string;
  /**
   * 是否有更新
   */
  hasUpdate: boolean;
  /**
   * 最新版本
   */
  latestVersion: string;
  /**
   * 提示信息
   */
  message?: string;
  /**
   * 更新地址
   */
  updateUrl?: string;
}
export interface ItemResponseDeveloperConfigBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: DeveloperConfig;
}
export interface VersionResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 更新频道
   */
  channel: string;
  /**
   * 应用名称
   */
  name: string;
  /**
   * 版本号
   */
  version: string;
}
export interface AIAssistantInfo {
  command?: string;
  detected: boolean;
  displayName: string;
  name: string;
  type: string;
}
export interface TerminalCountsResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 项目ID到终端数量的映射
   */
  counts: Record<string, number>;
}
export interface MoveNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 排序索引
   */
  orderIndex: number;
}
export interface UpdateNotePadBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 内容
   */
  content?: string;
  /**
   * 标签页名称
   */
  name?: string;
}
export interface UpdateProjectPriorityInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 项目优先级（1-5，null 表示取消置顶）
   */
  priority: number | null;
}
export interface UpdateProjectInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 项目描述
   */
  description: string;
  /**
   * 是否隐藏真实路径
   */
  hidePath: boolean;
  /**
   * 项目名称
   */
  name: string;
}
export interface CreateBranchBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 基础分支
   */
  base: string;
  /**
   * 同时创建 Worktree
   */
  createWorktree: boolean;
  /**
   * 分支名称
   */
  name: string;
}
export interface TerminalRenameInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 新的终端标签名
   */
  title: string;
}
export interface Worktree_create_request {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 基础分支
   */
  baseBranch: string;
  /**
   * 分支名称
   */
  branchName: string;
  /**
   * 是否创建新分支
   */
  createBranch: boolean;
}
export interface TerminalCreateInputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 终端列数
   */
  cols: number;
  /**
   * 终端行数
   */
  rows: number;
  /**
   * 插入到指定终端会话之后
   */
  insertAfterSessionId?: string;
  /**
   * 终端标题
   */
  title: string;
  /**
   * 工作目录
   */
  workingDir: string;
}
export interface BindWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * Worktree ID（null 表示解绑）
   */
  worktreeId?: string;
}
export interface Worktree_commit_request {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 提交信息
   */
  message: string;
}
export interface CapabilityReason {
  code: string;
  detail?: string;
}
export interface OperationCapabilities {
  branchesRead: boolean;
  branchesWrite: boolean;
  status: boolean;
  diff: boolean;
  worktreesRead: boolean;
  worktreesWrite: boolean;
  commit: boolean;
  fastForwardMerge: boolean;
  merge: boolean;
  rebase: boolean;
  squash: boolean;
}
export type GitEngine = 'builtin' | 'system' | 'unavailable';
export interface OperationEngines {
  branchesRead: GitEngine;
  branchesWrite: GitEngine;
  status: GitEngine;
  diff: GitEngine;
  worktreesRead: GitEngine;
  worktreesWrite: GitEngine;
  commit: GitEngine;
  fastForwardMerge: GitEngine;
  merge: GitEngine;
  rebase: GitEngine;
  squash: GitEngine;
}
export interface GitWorktreeCapabilityResult {
  id: string;
  operations: OperationCapabilities;
  engines: OperationEngines;
  reasons: CapabilityReason[] | null;
}
export interface GitCapabilityResult {
  repository: boolean;
  mode: string;
  operations: OperationCapabilities;
  engines: OperationEngines;
  reasons: CapabilityReason[] | null;
  worktrees: GitWorktreeCapabilityResult[] | null;
}
export interface ItemResponseGitCapabilityResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: GitCapabilityResult;
}
export type GitEnginePreference = 'auto' | 'builtin' | 'system';
export interface GitConfig {
  /** A URL to the JSON Schema for this object. */
  $schema?: string;
  readEngine: GitEnginePreference;
  writeEngine: GitEnginePreference;
  executable: string;
}
export interface SystemGitInfo {
  available: boolean;
  executable?: string;
  version?: string;
  error?: string;
}
export interface GitSettingsResult {
  readEngine: GitEnginePreference;
  writeEngine: GitEnginePreference;
  executable?: string;
  systemGit: SystemGitInfo;
}
export interface ItemResponseGitSettingsResultBody {
  /** A URL to the JSON Schema for this object. */
  $schema?: string;
  /** 响应对象 */
  item: GitSettingsResult;
}
export interface MergeBranchBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 源分支
   */
  sourceBranch: string;
  /** Squash 合并后立即提交 */
  commit: boolean;
  /** 提交信息（仅 squash 合并生效） */
  commitMessage: string;
  /**
   * 合并策略
   */
  strategy: 'merge' | 'rebase' | 'squash';
  /**
   * 目标分支
   */
  targetBranch: string;
}
export interface DeletedAt {
  Time: string;
  Valid: boolean;
}
export interface NotePadTable {
  content: string;
  createdAt: string;
  deletedAt: DeletedAt;
  id: string;
  name: string;
  orderIndex: number;
  projectId: string | null;
  updatedAt: string;
}
export interface ItemsResponseNotePadTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: NotePadTable[] | null;
}
export interface ItemResponseNotePadTableBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: NotePadTable;
}
export interface ItemResponseProjectBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: Project;
}
export interface RefreshAllResult {
  /**
   * 刷新失败数量
   */
  failed: number;
  /**
   * 刷新成功数量
   */
  updated: number;
}
export interface ItemResponseRefreshAllResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: RefreshAllResult;
}
export interface TerminalSessionView {
  aiAssistant?: AIAssistantInfo;
  cols: number;
  createdAt: string;
  encoding: string;
  id: string;
  lastActive: string;
  metadataCapturedAt?: string;
  processHasChildren?: boolean;
  processPid?: number;
  processStatus?: string;
  projectId: string;
  rows: number;
  runningCommand?: string;
  status: string;
  traffic?: {
    downstreamAvgBytesPerSec: number;
    downstreamBytes: number;
    downstreamRecentBytes: number;
    downstreamRecentAvgBytesPerSec: number;
    totalAvgBytesPerSec: number;
    totalBytes: number;
    totalRecentBytes: number;
    totalRecentAvgBytesPerSec: number;
    upstreamAvgBytesPerSec: number;
    upstreamBytes: number;
    upstreamRecentBytes: number;
    upstreamRecentAvgBytesPerSec: number;
  };
  title: string;
  orderIndex: number;
  workingDir: string;
  worktreeId: string;
  wsPath: string;
  wsUrl: string;
}
export interface ItemsResponseTerminalSessionViewBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: TerminalSessionView[] | null;
}
export interface ItemResponseTerminalSessionViewBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: TerminalSessionView;
}
export interface Worktree {
  branchName: string;
  createdAt: string;
  deletedAt: string | null;
  headCommit: string | null;
  headCommitDate: string | null;
  headCommitMessage: string | null;
  id: string;
  isBare: boolean;
  isMain: boolean;
  path: string;
  projectId: string;
  statusAhead: number | null;
  statusBehind: number | null;
  statusConflicts: number | null;
  statusModified: number | null;
  statusStaged: number | null;
  statusUntracked: number | null;
  statusUpdatedAt: string | null;
  updatedAt: string;
}
export interface ItemsResponseWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: Worktree[] | null;
}
export interface MessageItemsResponseWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应列表
   */
  items: Worktree[] | null;
  /**
   * 提示信息
   */
  message: string;
}
export interface ProjectTable {
  createdAt: string;
  defaultBranch: string;
  deletedAt: DeletedAt;
  description: string;
  hidePath: boolean;
  id: string;
  lastAccessedAt: string | null;
  lastSyncAt: string | null;
  name: string;
  path: string;
  priority: number | null;
  remoteUrl: string;
  updatedAt: string;
  worktreeBasePath: string;
}
export interface WorktreeTable {
  branchName: string;
  createdAt: string;
  deletedAt: DeletedAt;
  headCommit: string;
  headCommitDate: string | null;
  headCommitMessage: string;
  id: string;
  isBare: boolean;
  isMain: boolean;
  path: string;
  project?: ProjectTable;
  projectId: string;
  statusAhead: number;
  statusBehind: number;
  statusConflicts: number;
  statusModified: number;
  statusStaged: number;
  statusUntracked: number;
  statusUpdatedAt: string | null;
  updatedAt: string;
}
export interface DebugInfo {
  aiAssistant?: AIAssistantInfo;
  aiChunkCount?: number;
  cols: number;
  projectId: string;
  rows: number;
  scrollbackChunks: string[] | null;
  scrollbackChunksTimestamp: string[] | null;
  scrollbackLimit: number;
  scrollbackSize: number;
  sessionId: string;
  status: string;
  worktreeId: string;
}
export interface ItemResponseDebugInfoBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: DebugInfo;
}
export interface UploadImageResponse {
  /**
   * 文件名
   */
  fileName: string;
  /**
   * 文件路径
   */
  path: string;
  /**
   * 文件大小（字节）
   */
  size: number;
}
export interface ItemResponseUploadImageResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: UploadImageResponse;
}
export interface ItemResponseWorktreeBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: Worktree;
}
export interface BranchInfo {
  hasWorktree: boolean;
  headCommit: string;
  headCommitMessage: string;
  isCurrent: boolean;
  isRemote: boolean;
  name: string;
}
export interface BranchListResult {
  local: BranchInfo[] | null;
  remote: BranchInfo[] | null;
}
export interface ItemResponseBranchListResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: BranchListResult;
}
export interface CapturedChunk {
  data: string;
  size: number;
  timestamp: string;
}
export interface ItemResponseCapturedChunkBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: CapturedChunk;
}
export interface MergeResult {
  conflicts: string[] | null;
  message: string;
  success: boolean;
}
export interface ItemResponseMergeResultBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 响应对象
   */
  item: MergeResult;
}
declare global {
  interface Apis {
    health: {
      /**
       * ---
       *
       * [GET] 健康探测
       *
       * **path:** /api/v1/health
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      check<Config extends Alova2MethodConfig<MessageResponseBody>>(
        config?: Config
      ): Alova2Method<MessageResponseBody, 'health.check', Config>;
    };
    notepad: {
      /**
       * ---
       *
       * [GET] 获取记事板标签
       *
       * **path:** /api/v1/notepads
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 项目ID（为空表示全局笔记）
       *   projectId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemsResponseNotePadTableBody> & {
          params: {
            /**
             * 项目ID（为空表示全局笔记）
             */
            projectId?: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemsResponseNotePadTableBody, 'notepad.list', Config>;
      /**
       * ---
       *
       * [POST] 创建记事板标签
       *
       * **path:** /api/v1/notepads/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 内容
       *   content: string
       *   // 标签页名称
       *   name: string
       *   // 项目ID（为空表示全局笔记）
       *   projectId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          data: CreateNotePadBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.create', Config>;
      /**
       * ---
       *
       * [GET] 获取记事板标签详情
       *
       * **path:** /api/v1/notepads/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.get', Config>;
      /**
       * ---
       *
       * [POST] 删除记事板标签
       *
       * **path:** /api/v1/notepads/{id}/delete
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'notepad.delete', Config>;
      /**
       * ---
       *
       * [POST] 移动记事板标签顺序
       *
       * **path:** /api/v1/notepads/{id}/move
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 排序索引
       *   orderIndex: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      move<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
          data: MoveNotePadBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.move', Config>;
      /**
       * ---
       *
       * [POST] 更新记事板标签
       *
       * **path:** /api/v1/notepads/{id}/update
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 内容
       *   content?: string
       *   // 标签页名称
       *   name?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     content: string
       *     createdAt: string
       *     deletedAt: {
       *       Time: string
       *       Valid: boolean
       *     }
       *     id: string
       *     name: string
       *     orderIndex: number
       *     projectId: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<ItemResponseNotePadTableBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateNotePadBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseNotePadTableBody, 'notepad.update', Config>;
    };
    project: {
      /**
       * ---
       *
       * [GET] 项目列表
       *
       * **path:** /api/v1/projects
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     priority: number | null
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }> | null
       * }
       * ```
       */
      list<Config extends Alova2MethodConfig<ItemsResponseProjectBody>>(
        config?: Config
      ): Alova2Method<ItemsResponseProjectBody, 'project.list', Config>;
      /**
       * ---
       *
       * [POST] 创建项目
       *
       * **path:** /api/v1/projects/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 项目描述
       *   description: string
       *   // 是否隐藏真实路径
       *   hidePath?: boolean
       *   // 项目名称
       *   name: string
       *   // 本地项目目录路径（可非 Git 仓库）
       *   path: string
       *   // Worktree 基础路径（可选，默认为项目目录下的 .worktrees 子目录）
       *   worktreeBasePath?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     priority: number | null
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          data: CreateProjectInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.create', Config>;
      /**
       * ---
       *
       * [GET] 获取项目详情
       *
       * **path:** /api/v1/projects/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     priority: number | null
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      getById<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          pathParams: {
            id: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.getById', Config>;
      /**
       * ---
       *
       * [POST] 删除项目
       *
       * **path:** /api/v1/projects/{id}/delete
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'project.delete', Config>;
      /**
       * ---
       *
       * [POST] 更新项目优先级
       *
       * **path:** /api/v1/projects/{id}/priority
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 项目优先级（1-5，null 表示取消置顶）
       *   priority: number | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     priority: number | null
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      updatePriority<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateProjectPriorityInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.updatePriority', Config>;
      /**
       * ---
       *
       * [POST] 编辑项目
       *
       * **path:** /api/v1/projects/{id}/update
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 项目描述
       *   description: string
       *   // 是否隐藏真实路径
       *   hidePath: boolean
       *   // 项目名称
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     createdAt: string
       *     defaultBranch: string | null
       *     deletedAt: string | null
       *     description: string | null
       *     hidePath: boolean
       *     id: string
       *     lastSyncAt: string | null
       *     name: string
       *     path: string
       *     priority: number | null
       *     remoteUrl: string | null
       *     updatedAt: string
       *     worktreeBasePath: string | null
       *   }
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<ItemResponseProjectBody> & {
          pathParams: {
            id: string;
          };
          data: UpdateProjectInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseProjectBody, 'project.update', Config>;
      /**
       * [GET] 获取项目 Git 能力
       *
       * **path:** /api/v1/projects/{projectId}/git-capabilities
       */
      gitCapabilities<
        Config extends Alova2MethodConfig<ItemResponseGitCapabilityResultBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseGitCapabilityResultBody, 'project.gitCapabilities', Config>;
    };
    branch: {
      /**
       * ---
       *
       * [GET] 获取分支列表
       *
       * **path:** /api/v1/projects/{projectId}/branches
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 强制刷新，忽略缓存
       *   force?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     local: Array<{
       *       hasWorktree: boolean
       *       headCommit: string
       *       headCommitMessage: string
       *       isCurrent: boolean
       *       isRemote: boolean
       *       name: string
       *     }> | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     remote: Array<{
       *       hasWorktree: boolean
       *       headCommit: string
       *       headCommitMessage: string
       *       isCurrent: boolean
       *       isRemote: boolean
       *       name: string
       *     }> | null
       *   }
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemResponseBranchListResultBody> & {
          pathParams: {
            projectId: string;
          };
          params: {
            /**
             * 强制刷新，忽略缓存
             */
            force?: boolean;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseBranchListResultBody, 'branch.list', Config>;
      /**
       * ---
       *
       * [POST] 创建分支
       *
       * **path:** /api/v1/projects/{projectId}/branches/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 基础分支
       *   base: string
       *   // 同时创建 Worktree
       *   createWorktree: boolean
       *   // 分支名称
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
          };
          data: CreateBranchBody;
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'branch.create', Config>;
      /**
       * ---
       *
       * [POST] 删除分支
       *
       * **path:** /api/v1/projects/{projectId}/branches/{branchName}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   branchName: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 强制删除
       *   force?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
            branchName: string;
          };
          params: {
            /**
             * 强制删除
             */
            force?: boolean;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'branch.delete', Config>;
      /**
       * ---
       *
       * [POST] 合并分支
       *
       * **path:** /api/v1/worktrees/{id}/merge
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // Squash 合并后立即提交
       *   commit: boolean
       *   // 提交信息（仅 squash 合并生效）
       *   commitMessage: string
       *   // 源分支
       *   sourceBranch: string
       *   // 合并策略
       *   strategy: 'merge' | 'rebase' | 'squash'
       *   // 目标分支
       *   targetBranch: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     conflicts: string[] | null
       *     message: string
       *     success: boolean
       *   }
       * }
       * ```
       */
      merge<
        Config extends Alova2MethodConfig<ItemResponseMergeResultBody> & {
          pathParams: {
            id: string;
          };
          data: MergeBranchBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseMergeResultBody, 'branch.merge', Config>;
    };
    worktree: {
      /**
       * ---
       *
       * [POST] 刷新所有 Worktree 状态
       *
       * **path:** /api/v1/projects/{projectId}/refresh-all-worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // 刷新失败数量
       *     failed: number
       *     // 刷新成功数量
       *     updated: number
       *   }
       * }
       * ```
       */
      refreshAllByProject<
        Config extends Alova2MethodConfig<ItemResponseRefreshAllResultBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseRefreshAllResultBody, 'worktree.refreshAllByProject', Config>;
      /**
       * ---
       *
       * [POST] 同步 Worktree
       *
       * **path:** /api/v1/projects/{projectId}/sync-worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   items: Worktree[] | null
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      syncByProject<
        Config extends Alova2MethodConfig<MessageItemsResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageItemsResponseWorktreeBody, 'worktree.syncByProject', Config>;
      /**
       * ---
       *
       * [GET] 获取 Worktree 列表
       *
       * **path:** /api/v1/projects/{projectId}/worktrees
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     headCommitMessage: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      listByProject<
        Config extends Alova2MethodConfig<ItemsResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemsResponseWorktreeBody, 'worktree.listByProject', Config>;
      /**
       * ---
       *
       * [POST] 创建 Worktree
       *
       * **path:** /api/v1/projects/{projectId}/worktrees/create
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 基础分支
       *   baseBranch: string
       *   // 分支名称
       *   branchName: string
       *   // 是否创建新分支
       *   createBranch: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     headCommitMessage: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
          data: Worktree_create_request;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.create', Config>;
      /**
       * ---
       *
       * [POST] 刷新 Worktree 的提交信息
       *
       * **path:** /api/v1/projects/{projectId}/worktrees/refresh-commits
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     headCommitMessage: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }> | null
       * }
       * ```
       */
      refreshCommitInfo<
        Config extends Alova2MethodConfig<ItemsResponseWorktreeBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemsResponseWorktreeBody, 'worktree.refreshCommitInfo', Config>;
      /**
       * ---
       *
       * [POST] 删除 Worktree
       *
       * **path:** /api/v1/worktrees/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   force?: boolean
       *   deleteBranch?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            id: string;
          };
          params: {
            force?: boolean;
            deleteBranch?: boolean;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'worktree.delete', Config>;
      /**
       * ---
       *
       * [POST] 提交 Worktree 更改
       *
       * **path:** /api/v1/worktrees/{id}/commit
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提交信息
       *   message: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     headCommitMessage: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      commit<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            id: string;
          };
          data: Worktree_commit_request;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.commit', Config>;
      /**
       * ---
       *
       * [POST] 刷新 Worktree 状态
       *
       * **path:** /api/v1/worktrees/{id}/refresh-status
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     branchName: string
       *     createdAt: string
       *     deletedAt: string | null
       *     headCommit: string | null
       *     headCommitDate: string | null
       *     headCommitMessage: string | null
       *     id: string
       *     isBare: boolean
       *     isMain: boolean
       *     path: string
       *     projectId: string
       *     statusAhead: number | null
       *     statusBehind: number | null
       *     statusConflicts: number | null
       *     statusModified: number | null
       *     statusStaged: number | null
       *     statusUntracked: number | null
       *     statusUpdatedAt: string | null
       *     updatedAt: string
       *   }
       * }
       * ```
       */
      refreshStatus<
        Config extends Alova2MethodConfig<ItemResponseWorktreeBody> & {
          pathParams: {
            id: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseWorktreeBody, 'worktree.refreshStatus', Config>;
    };
    terminalSession: {
      /**
       * ---
       *
       * [GET] 获取终端会话列表
       *
       * **path:** /api/v1/projects/{projectId}/terminals
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应列表
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     aiAssistant?: {
       *       command?: string
       *       detected: boolean
       *       displayName: string
       *       name: string
       *       type: string
       *     }
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     processHasChildren?: boolean
       *     processPid?: number
       *     processStatus?: string
       *     projectId: string
       *     rows: number
       *     runningCommand?: string
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }> | null
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<ItemsResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemsResponseTerminalSessionViewBody, 'terminalSession.list', Config>;
      /**
       * ---
       *
       * [POST] 关闭终端会话
       *
       * **path:** /api/v1/projects/{projectId}/terminals/{sessionId}/close
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      close<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          pathParams: {
            projectId: string;
            sessionId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'terminalSession.close', Config>;
      /**
       * ---
       *
       * [POST] 终端标签重命名
       *
       * **path:** /api/v1/projects/{projectId}/terminals/{sessionId}/rename
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 新的终端标签名
       *   title: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     aiAssistant?: {
       *       command?: string
       *       detected: boolean
       *       displayName: string
       *       name: string
       *       type: string
       *     }
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     processHasChildren?: boolean
       *     processPid?: number
       *     processStatus?: string
       *     projectId: string
       *     rows: number
       *     runningCommand?: string
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }
       * }
       * ```
       */
      rename<
        Config extends Alova2MethodConfig<ItemResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
            sessionId: string;
          };
          data: TerminalRenameInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseTerminalSessionViewBody, 'terminalSession.rename', Config>;
      /**
       * ---
       *
       * [POST] 创建终端会话
       *
       * **path:** /api/v1/projects/{projectId}/worktrees/{worktreeId}/terminals
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   projectId: string
       *   worktreeId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 终端列数
       *   cols: number
       *   // 终端行数
       *   rows: number
       *   // 终端标题
       *   title: string
       *   // 工作目录
       *   workingDir: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     aiAssistant?: {
       *       command?: string
       *       detected: boolean
       *       displayName: string
       *       name: string
       *       type: string
       *     }
       *     cols: number
       *     createdAt: string
       *     encoding: string
       *     id: string
       *     lastActive: string
       *     processHasChildren?: boolean
       *     processPid?: number
       *     processStatus?: string
       *     projectId: string
       *     rows: number
       *     runningCommand?: string
       *     status: string
       *     title: string
       *     workingDir: string
       *     worktreeId: string
       *     wsPath: string
       *     wsUrl: string
       *   }
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<ItemResponseTerminalSessionViewBody> & {
          pathParams: {
            projectId: string;
            worktreeId: string;
          };
          data: TerminalCreateInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseTerminalSessionViewBody, 'terminalSession.create', Config>;
      /**
       * ---
       *
       * [GET] 获取所有项目的终端数量统计
       *
       * **path:** /api/v1/terminals/counts
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 项目ID到终端数量的映射
       *   counts: Record<string, number>
       * }
       * ```
       */
      terminalCounts<Config extends Alova2MethodConfig<TerminalCountsResponseBody>>(
        config?: Config
      ): Alova2Method<TerminalCountsResponseBody, 'terminalSession.terminalCounts', Config>;
      /**
       * ---
       *
       * [GET] 触发 resize 并捕获下一个输出 chunk
       *
       * **path:** /api/v1/terminals/{sessionId}/capture
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 超时时间（秒），默认为 2 秒，0 表示使用默认值
       *   timeout?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     data: string
       *     size: number
       *     timestamp: string
       *   }
       * }
       * ```
       */
      captureChunk<
        Config extends Alova2MethodConfig<ItemResponseCapturedChunkBody> & {
          pathParams: {
            sessionId: string;
          };
          params: {
            /**
             * 超时时间（秒），默认为 2 秒，0 表示使用默认值
             */
            timeout?: number;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseCapturedChunkBody, 'terminalSession.captureChunk', Config>;
      /**
       * ---
       *
       * [GET] 获取终端调试信息（包含完整输出内容）
       *
       * **path:** /api/v1/terminals/{sessionId}/debug
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   sessionId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     aiAssistant?: {
       *       command?: string
       *       detected: boolean
       *       displayName: string
       *       name: string
       *       type: string
       *     }
       *     aiChunkCount?: number
       *     cols: number
       *     projectId: string
       *     rows: number
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     scrollbackChunks: string[] | null
       *     // [params1] start
       *     // [items] start
       *     // [items] end
       *     // [params1] end
       *     scrollbackChunksTimestamp: string[] | null
       *     scrollbackLimit: number
       *     scrollbackSize: number
       *     sessionId: string
       *     status: string
       *     worktreeId: string
       *   }
       * }
       * ```
       */
      debug<
        Config extends Alova2MethodConfig<ItemResponseDebugInfoBody> & {
          pathParams: {
            sessionId: string;
          };
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseDebugInfoBody, 'terminalSession.debug', Config>;
    };
    system: {
      /**
       * [GET] 获取 Git 引擎设置
       *
       * **path:** /api/v1/system/git-settings
       */
      gitSettingsGet<
        Config extends Alova2MethodConfig<ItemResponseGitSettingsResultBody> & {
          params?: {
            refresh?: boolean;
          };
        },
      >(
        config?: Config
      ): Alova2Method<ItemResponseGitSettingsResultBody, 'system.gitSettingsGet', Config>;
      /**
       * [POST] 更新 Git 引擎设置
       *
       * **path:** /api/v1/system/git-settings/update
       */
      gitSettingsUpdate<
        Config extends Alova2MethodConfig<ItemResponseGitSettingsResultBody> & {
          data: GitConfig;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseGitSettingsResultBody, 'system.gitSettingsUpdate', Config>;
      /**
       * ---
       *
       * [GET] 检查版本更新
       *
       * **path:** /api/v1/system/check-update
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 当前版本
       *   currentVersion: string
       *   // 是否有更新
       *   hasUpdate: boolean
       *   // 最新版本
       *   latestVersion: string
       *   // 提示信息
       *   message?: string
       *   // 更新地址
       *   updateUrl?: string
       * }
       * ```
       */
      checkUpdate<Config extends Alova2MethodConfig<CheckUpdateResponseBody>>(
        config?: Config
      ): Alova2Method<CheckUpdateResponseBody, 'system.checkUpdate', Config>;
      /**
       * ---
       *
       * [GET] 获取开发者调试配置
       *
       * **path:** /api/v1/system/developer-config
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // A URL to the JSON Schema for this object.
       *     $schema?: string
       *     enableTerminalScrollback: boolean
       *     enableTerminalStateSnapshot: boolean
       *     webSessionCodexClientName: string
       *     webSessionCodexClientTitle: string
       *     webSessionCodexClientVersion: string
       *     webSessionCodexDefaultModel: string
       *     webSessionCodexDefaultPermissionLevel: string
       *     webSessionCodexDefaultReasoningEffort: string
       *     webSessionCodexDefaultSyncMode: string
       *     webSessionActiveCallTimeout: WebSessionActiveCallTimeoutConfig
       *   }
       * }
       * ```
       */
      developerConfigGet<Config extends Alova2MethodConfig<ItemResponseDeveloperConfigBody>>(
        config?: Config
      ): Alova2Method<ItemResponseDeveloperConfigBody, 'system.developerConfigGet', Config>;
      /**
       * ---
       *
       * [POST] 更新开发者调试配置
       *
       * **path:** /api/v1/system/developer-config/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   enableTerminalScrollback: boolean
       *   enableTerminalStateSnapshot: boolean
       *   webSessionCodexClientName: string
       *   webSessionCodexClientTitle: string
       *   webSessionCodexClientVersion: string
       *   webSessionCodexDefaultModel: string
       *   webSessionCodexDefaultPermissionLevel: string
       *   webSessionCodexDefaultReasoningEffort: string
       *   webSessionCodexDefaultSyncMode: string
       *   webSessionActiveCallTimeout: WebSessionActiveCallTimeoutConfig
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      developerConfigUpdate<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: DeveloperConfig;
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.developerConfigUpdate', Config>;
      /**
       * ---
       *
       * [POST] 使用指定编辑器打开目录
       *
       * **path:** /api/v1/system/open-editor
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 自定义命令，使用 ${path} 作为路径占位符
       *   customCommand?: string
       *   // 目标编辑器(vscode/cursor/trae/zed/custom)
       *   editor: string
       *   // 目标路径
       *   path: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      openEditor<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: OpenEditorInputBody;
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.openEditor', Config>;
      /**
       * ---
       *
       * [POST] 打开文件管理器
       *
       * **path:** /api/v1/system/open-explorer
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 目标路径
       *   path: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      openExplorer<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: OpenPathInputBody;
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.openExplorer', Config>;
      /**
       * ---
       *
       * [POST] 打开终端
       *
       * **path:** /api/v1/system/open-terminal
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 目标路径
       *   path: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      openTerminal<
        Config extends Alova2MethodConfig<MessageResponseBody> & {
          data: OpenPathInputBody;
        },
      >(
        config: Config
      ): Alova2Method<MessageResponseBody, 'system.openTerminal', Config>;
      /**
       * ---
       *
       * [GET] 获取应用版本信息
       *
       * **path:** /api/v1/system/version
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 更新频道
       *   channel: string
       *   // 应用名称
       *   name: string
       *   // 版本号
       *   version: string
       * }
       * ```
       */
      version<Config extends Alova2MethodConfig<VersionResponseBody>>(
        config?: Config
      ): Alova2Method<VersionResponseBody, 'system.version', Config>;
    };
    upload: {
      /**
       * ---
       *
       * [POST] 上传剪贴板图片
       *
       * **path:** /api/v1/upload/clipboard-image
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 图片数据（base64 编码）
       *   data: string
       *   // 文件名
       *   fileName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 响应对象
       *   item: {
       *     // 文件名
       *     fileName: string
       *     // 文件路径
       *     path: string
       *     // 文件大小（字节）
       *     size: number
       *   }
       * }
       * ```
       */
      clipboardImage<
        Config extends Alova2MethodConfig<ItemResponseUploadImageResponseBody> & {
          data: UploadClipboardImageInputBody;
        },
      >(
        config: Config
      ): Alova2Method<ItemResponseUploadImageResponseBody, 'upload.clipboardImage', Config>;
    };
  }

  var Apis: Apis;
}
